version: "3.8"

services:
  webhook:
    build:
    context: .
    args:
      PORT: ${PORT}
    dockerfile: Dockerfile
    image: webhook:latest
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    env_file: .env
    container_name: webhook_server
    networks:
      - webhook_net
    depends_on:
      - database
  database:
    image: "postgres:alpine"
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    POSTGRES_USER: ${DATABASE_USER}
    POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    container_name: webhook_database
    networks:
      - webhook_net
networks:
  webhook_net:
